### ISSUE TITLE
Disallow certain quickchats after actions, also allow time after action happens that quickchat is disallowed to be configured

### ISSUE THREAD

**Issue by henxdl** [JulienML/BetterChat#1]
First off, I think there should be a whitelist and a blacklist, e.g. the options would be 'Always Allowed Chats', 'Always Blocked Chats', 'Always Allow when X happens', and always block when X happens. I also think that the time that the chat is blocked after the event should be configurable. And finally, I think that if an ally or you touches the ball after a shot is taken, causing it to still go in should be another event (im not sure if this is counted as an owngoal)

**Comment by JulienML** [comment]
Thank you for your suggestion. Including a whitelist is a good idea, I think I will add it in the next major update. Concerning the time that the chat is blocked after an event, at the moment it is set to 5 seconds and is only used for the saves; after a goal or a pass, it is reset on the next kick-off and for the 'before kick-off' messages, they are active from the end of the replay to the kick-off, but I can still make it configurable. I am also thinking about an option to not count a goal/pass if an opponent touch it before it reach the goal/the ally, I think it will be available on the next update :)

**Comment by JulienML** [comment]
- You can now allow or disallow every quickchat as you want (as if there were a whitelist and a blacklist). (Since [v2.0.0](https://github.com/JulienML/BetterChat/releases/tag/v2.0.0))
- The time that the chat is blocked after an event is configurable for the "after a save" category (for the other categories, it is automatic as explained just above). (Since [v1.1.0](https://github.com/JulienML/BetterChat/releases/tag/v1.1.0))
- You can also choose to count or not a goal/pass if the ball is touched by an opponent before it reaches the goal/the striker. (Since [v1.1.0](https://github.com/JulienML/BetterChat/releases/tag/v1.1.0))

Thank you for your suggestions, I close this issue :)
